FROM itzg/gvm

MAINTAINER itzg

//RUN ["/run", "install", "springboot"]

//ADD run /run
//ENTRYPOINT ["/run"]

///VOLUME ["/home/spring"]
//ADD app.groovy /home/spring/app.groovy


//WORKDIR /home/spring

//CMD ["run", "app.groovy"]
